### ISSUE TITLE
Changing colors does not reflect.

### ISSUE THREAD

**Issue by Ramzy993** [open-craft/edx-simple-theme#13]
Hello, 
I tried to change several colors and it does not reflect. 

notes:
* I also changed the default theme to edx-simple-theme

* After changing I do 
- sudo /opt/bitnami/apps/edx/bin/edxapp-update-assets-lms
- sudo /opt/bitnami/ctlscript.sh restart apache

and it does not reflect

is there any missing step?

**Comment by lgp171188** [comment]
@Ramzy993, can you provide more details on how you are using this theme? Have you enabled comprehensive theming by setting the `ENABLE_COMPREHENSIVE_THEMING` to `true`, updated `COMPREHENSIVE_THEME_DIRS` to include the parent directory of the cloned theme repository and set the value of the `DEFAULT_SITE_THEME` variable to the name of the cloned directory?

The files in this repository cannot be directly used as an Open edX comprehensive theme and require deployment through the [simple_theme](https://github.com/edx/configuration/tree/open-release/juniper.master/playbooks/roles/simple_theme) Ansible role.

If you are not using that Ansible role or don't want to use it, you will have to create a few additional files after cloning this repository, mimicking what the `simple_theme` role does.

* `lms/static/sass/_lms-overrides.scss`
```scss
@import 'common-variables';

/* You can add any custom CSS/SASS here */
```
* `lms/static/sass/common-variables.scss`
```scss
/* Define all your SASS variable overrides here */
```
Once you have created these files with the appropriate content, you can run the command to update the assets. The theme customizations corresponding to the SASS variables overrides defined in `common-variables.scss` and the custom styles defined in `_lms-overrides.scss` should get applied now.

Please try these steps out and let us know if you still have the same issue.
