### ISSUE TITLE
How to implement this theme to my open edx instance

### ISSUE THREAD

**Issue by TSriHarshaVardhan** [open-craft/edx-simple-theme#7]
Please guide me how to install and customize and implement this theme to my open edx instance.
I'm using OpenEdx Ironwood 2 version
Please provide some screenshots of this theme.
Thank you.

**Comment by antoviaque** [comment]
@TSriHarshaVardhan To get help about theming customization, the best is to post on the Open edX forum: https://discuss.openedx.org/

This theme is really basic - the best way to see it in action is to spin up a trial instance on our hosting platform: https://opencraft.com/hosting/

It would be useful to include a screenshot though yes - if you do create an instance there, would you be willing to take that screenshot, and post a PR here to add it to the repository README? That would be a very welcomed contribution!

In the meantime, I'm closing this ticket as this isn't a bug.
